global using System;
global using System.Collections.Generic;
global using System.Linq;
global using MediatR;
global using Microsoft.EntityFrameworkCore;
global using PatientInformation.Api.Filters;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using PatientInformation.Domain.Common;
